### ISSUE TITLE
Firekylin-系统安装时  出现数据表导入失败 ，控制台查看具体错误信息

### ISSUE THREAD

**Issue by dxhack** [firekylin/firekylin#370]
发现没有错误信息啊。。小白一个。。求大神们指教

**Comment by lizheming** [comment]
```
/root/.pm2/logs/firekylin-error-0.log last 15 lines:
0|firekyli | at Connection.connect (/root/firekylin/node_modules/mysql/lib/Connection.js:136:18)
0|firekyli | at /root/firekylin/node_modules/thinkjs/lib/adapter/socket/mysql.js:117:25
0|firekyli | at _class.run (/root/firekylin/node_modules/thinkjs/lib/util/await.js:52:40)
0|firekyli | at Object.think.await (/root/firekylin/node_modules/thinkjs/lib/core/think.js:1032:25)
0|firekyli | at _class.getConnection (/root/firekylin/node_modules/thinkjs/lib/adapter/socket/mysql.js:114:18)
0|firekyli | at _class._callee2$ (/root/firekylin/node_modules/thinkjs/lib/adapter/socket/mysql.js:168:27)
0|firekyli | at tryCatch (/root/firekylin/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:88:40)
0|firekyli | at GeneratorFunctionPrototype.invoke [as _invoke] (/root/firekylin/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:341:22)
0|firekyli | at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/root/firekylin/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:
121:21)
0|firekyli | at step (/root/firekylin/node_modules/thinkjs/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
0|firekyli | at /root/firekylin/node_modules/thinkjs/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
0|firekyli | at Promise._execute (/root/firekylin/node_modules/bluebird/js/release/debuggability.js:272:9)
0|firekyli | at Promise._resolveFromExecutor (/root/firekylin/node_modules/bluebird/js/release/promise.js:473:18)
0|firekyli | at new Promise (/root/firekylin/node_modules/bluebird/js/release/promise.js:77:14)
0|firekyli | at _class.<anonymous> (/root/firekylin/node_modules/thinkjs/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
```

**Comment by lizheming** [comment]
@dxhack 好像是教程有点问题，再安装的时候你再执行下 `service mysqld restart` 再安装试试，应该是 MySQL 没启起来的问题。

**Comment by Trilliean** [comment]
刚才遇到了类似的问题，可以先去看一下/root/.pm2/logs/firekylin-error-0.log文件里的错误信息，我的是：
`Error: ER_BAD_DB_ERROR: Unknown database 'firekylin'`
所以去手动创建下firekylin数据库就行。如果还不行，可以重启mysql服务试试。

**Comment by ddhhz** [comment]
Closed by #380

**Comment by NLxs** [comment]
sudo systemctl restart mysqld 以后还是不行
