### ISSUE TITLE
linux 服务器安装的nodejs的方式

### ISSUE THREAD

**Issue by starstudy** [firekylin/firekylin#400]
我是采用的非源码方式安装，但是运行pm2的时候，提示运行失败，然后看了项目的具体显示发现，firekylin找不到nodejs的版本，请问这种问题该如何解决呢
![image](https://user-images.githubusercontent.com/21272666/28805133-6a613316-769a-11e7-8130-eb904d7b83b0.png)
而实际上pm2文件中的cwd我也改过了，但是没有生效
![image](https://user-images.githubusercontent.com/21272666/28805146-842f2e92-769a-11e7-8a6f-e069d4a35c10.png)

**Comment by jerrybendy** [comment]
为嘛 `script path` 和 `exec cwd` 差这么多……

**Comment by starstudy** [comment]
这也是我比较疑惑的，对于cwd的路径配置，应该改掉pm2就可以了，下面是我pm2的配置
![image](https://user-images.githubusercontent.com/21272666/28805257-3d517f2e-769b-11e7-8580-8b93111e6182.png)

**Comment by jerrybendy** [comment]
配置看起来是没有什么问题的，启动 `pm2 start pm2.json`。如果继续报错的话尽量看下错误信息是什么，把错误信息贴出来看看

**Comment by starstudy** [comment]
![image](https://user-images.githubusercontent.com/21272666/28808847-eca975d8-76b1-11e7-80ab-9ecaf045dc51.png)

通过pm2 logs查看的日志

**Comment by jerrybendy** [comment]
看来是代码报错了。错误信息可否再贴得完整些，刚好错误信息里面最重要部分没有贴出来……

@lizheming 有没有时间看一下

**Comment by starstudy** [comment]
```
[root@star .pm2]# vi pm2.log 
2017-07-31 13:03:28: ===============================================================================
2017-07-31 13:03:28: --- New PM2 Daemon started ----------------------------------------------------
2017-07-31 13:03:28: Time                 : Mon Jul 31 2017 13:03:28 GMT-0400 (EDT)
2017-07-31 13:03:28: PM2 version          : 2.6.1
2017-07-31 13:03:28: Node.js version      : 6.11.1
2017-07-31 13:03:28: Current arch         : x64
2017-07-31 13:03:28: PM2 home             : /root/.pm2
2017-07-31 13:03:28: PM2 PID file         : /root/.pm2/pm2.pid
2017-07-31 13:03:28: RPC socket file      : /root/.pm2/rpc.sock
2017-07-31 13:03:28: BUS socket file      : /root/.pm2/pub.sock
2017-07-31 13:03:28: Application log path : /root/.pm2/logs
2017-07-31 13:03:28: Process dump file    : /root/.pm2/dump.pm2
2017-07-31 13:03:28: Concurrent actions   : 2
2017-07-31 13:03:28: SIGTERM timeout      : 1600
2017-07-31 13:03:28: ===============================================================================
2017-07-31 13:07:23: Starting execution sequence in -fork mode- for app name:firekylin id:0
2017-07-31 13:07:23: App name:firekylin id:0 online
2017-07-31 13:07:23: Error: spawn node ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```
这些就是所有的堆栈信息了，其余的基本都是重复这个错误

**Comment by starstudy** [comment]
我推测很可能是环境的适配原因导致，pm2 Or nodejs，不得而知，在这上面，我是小白。im  java 出身的。不过问题咱们到可以一起探讨解决下，也可能对该blog system有帮助，3Q

**Comment by jerrybendy** [comment]
你可以尝试使用 `node www/production.js` 命令启动，如果可以成功运行的话基本上可以排除是 node 的问题。从错误信息上确实也没有得到多少有价值的内容，只能先试试看了。

**Comment by starstudy** [comment]
好的，多谢，试了下，单独

>  node www/production.js

 是可行的

**Comment by lizheming** [comment]
cwd 不一致的问题，从截图1和截图2的表征来看看起来像是你未修改 pm2.json 文件启动了，然后修改了 pm2.json 文件但没生效。直接杀掉这个守护再重启下试试吧。

**Comment by jerrybendy** [comment]
老大说得对  😉

**Comment by starstudy** [comment]
谢谢

**Comment by ddhhz** [comment]
解决了吗？
