### ISSUE TITLE
TypeError: Cannot read property 'featuredImage' of null

### ISSUE THREAD

**Issue by yujintao529** [firekylin/firekylin#415]
hi，你好 
默认的知道博客为什么每次点击都会出现这个错误？
看了下pm2的日志：
```
TypeError: Cannot read property 'featuredImage' of null
0|firekyli |     at _class._callee2$ (/Users/yujintao/Documents/software/firekylin/app/home/controller/post.js:282:54)
0|firekyli |     at tryCatch (/Users/yujintao/Documents/software/firekylin/node_modules/regenerator-runtime/runtime.js:65:40)
0|firekyli |     at Generator.invoke [as _invoke] (/Users/yujintao/Documents/software/firekylin/node_modules/regenerator-runtime/runtime.js:303:22)
0|firekyli |     at Generator.prototype.(anonymous function) [as next] (/Users/yujintao/Documents/software/firekylin/node_modules/regenerator-runtime/runtime.js:117:21)
0|firekyli |     at step (/Users/yujintao/Documents/software/firekylin/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
0|firekyli |     at /Users/yujintao/Documents/software/firekylin/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
0|firekyli |     at <anonymous>
0|firekyli |     at process._tickDomainCallback (internal/process/next_tick.js:208:7)
```

**Comment by lizheming** [comment]
fixed at https://github.com/firekylin/firekylin/pull/414

**Comment by yujintao529** [comment]
ok，thanks

**Comment by ddhhz** [comment]
你可以到后台打开这篇文章再保存一下即可修复。
