### ISSUE TITLE
pm2 startOrReload pm2.json 时出错

### ISSUE THREAD

**Issue by zkTom** [firekylin/firekylin#429]
是按照腾讯云实验的步骤来的 在ubuntu16.04 就会报出下面的错误。
```
 2017-09-23 09:54:58: Error: spawn node ENOENT
PM2        |     at exports._errnoException (util.js:1024:11)
PM2        |     at Process.ChildProcess._handle.onexit `(internal/child_process.js:192:19)`
PM2        |     at onErrorNT (internal/child_process.js:374:16)
PM2        |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
PM2        |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by lizheming** [comment]
node 版本是多少，怎么安装的？pm2 的版本呢？

**Comment by zkTom** [comment]
node 8.11  pm2就是官方最新版本的2.7.1

**Comment by lizheming** [comment]
8.11 ? 自己编译的？目前官方最新的不是 8.5 么？

**Comment by zkTom** [comment]
node(8.2.1)  pm2(2.7.0)
node很早之前就装过了，pm2也是，不过以防万一更新了一下，服务器上pm2用来部署别的项目是没问题的，所以我有点搞不明白。

**Comment by lizheming** [comment]
`node www/production.js` 启动看看有没有问题，如果没问题贴一下 `pm2.json` 的配置。

**Comment by zkTom** [comment]
```
  1 {
  2   "apps": [{
  3     "name": "firekylin",
  4     "script": "www/production.js",
  5     "cwd": "/root/firekylin/",
  6     "exec_mode": "fork",
  7     "max_memory_restart": "1G",
  8     "autorestart": true,
  9     "node_args": [],
 10     "args": [],
 11     "env": {
 12
 13     }
 14   }]
 15 }

```

**Comment by lizheming** [comment]
看起来配置文件没问题，单独启动没问题的话应该还是你的环境的问题。

**Comment by zkTom** [comment]
找不出环境问题出在哪里，果断删了原来的node,装上最新的版本。现在是可以跑通的。（貌似不是解决问题的根本办法）

**Comment by lizheming** [comment]
嗯，好的，解决了我就先关闭 issue 了~
