### ISSUE TITLE
重启了Firekylin服务之后502

### ISSUE THREAD

**Issue by haima2** [firekylin/firekylin#529]
今天执行了

```bash
pm2 restart firekylin
```

之后访问就一直是502，怎么办？
网址是：https://blog.ylhack.cf
Nginx错误日志如下
```
2018/05/13 23:24:19 [error] 12988#0: *95 connect() failed (111: Connection refused) while connecting to upstream, client: **.**.***.***, server: blog.ylhack.cf, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8360/", host: "blog.ylhack.cf"
```

**Comment by wei** [comment]
麻烦 `pm2 logs` 看一下 `pm2` 的错误日志。

**Comment by haima2** [comment]
```
0|firekyli |     at createScript (vm.js:246:10)
0|firekyli |     at Object.runInThisContext (vm.js:298:10)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:646:28)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:589:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:626:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at exports.interopRequire (/www/wwwroot/blog/blog/node_modules/think-loader/loader/util.js:14:13)
0|firekyli |     at allowExtends.forEach.type (/www/wwwroot/blog/blog/node_modules/think-loader/loader/extend.js:46:20)
0|firekyli |     at Array.forEach (<anonymous>)
0|firekyli |     at Object.load (/www/wwwroot/blog/blog/node_modules/think-loader/loader/extend.js:40:18)
0|firekyli |     at Loader.loadExtend (/www/wwwroot/blog/blog/node_modules/think-loader/index.js:86:19)
0|firekyli |     at thinkLoader.loadExtend (/www/wwwroot/blog/blog/node_modules/thinkjs/lib/loader.js:62:31)

```
这是pm2的错误日志

**Comment by haima2** [comment]
```
[TAILING] Tailing last 100 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 100 lines:
PM2        | [2018-05-05 18:14:02] PM2 log: App [firekylin] with id [0] and pid [14780], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:14:02] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:14:02] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:14:02] PM2 log: App [firekylin] with id [0] and pid [14790], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:14:02] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:14:02] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:14:02] PM2 log: App [firekylin] with id [0] and pid [14800], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:14:02] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:14:02] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:14:03] PM2 log: App [firekylin] with id [0] and pid [14810], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:14:03] PM2 log: Script /www/wwwroot/blog/blogproduction.js had too many unstable restarts (16). Stopped. "errored"
PM2        | [2018-05-05 18:14:26] PM2 log: Stopping app:firekylin id:0
PM2        | [2018-05-05 18:14:26] PM2 error: app=firekylin id=0 does not have a pid
PM2        | [2018-05-05 18:16:02] PM2 log: Process 0 in a stopped status, starting it
PM2        | [2018-05-05 18:16:02] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:02] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:02] PM2 log: App [firekylin] with id [0] and pid [15166], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:02] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:02] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:02] PM2 log: App [firekylin] with id [0] and pid [15176], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:02] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:02] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:03] PM2 log: App [firekylin] with id [0] and pid [15186], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:03] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:03] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:03] PM2 log: App [firekylin] with id [0] and pid [15196], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:03] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:03] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:03] PM2 log: App [firekylin] with id [0] and pid [15206], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:03] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:03] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:03] PM2 log: App [firekylin] with id [0] and pid [15216], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:03] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:03] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:03] PM2 log: App [firekylin] with id [0] and pid [15226], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:03] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:03] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:03] PM2 log: App [firekylin] with id [0] and pid [15236], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:03] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:03] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:03] PM2 log: App [firekylin] with id [0] and pid [15246], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:03] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:03] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:04] PM2 log: App [firekylin] with id [0] and pid [15256], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:04] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:04] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:04] PM2 log: App [firekylin] with id [0] and pid [15266], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:04] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:04] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:04] PM2 log: App [firekylin] with id [0] and pid [15276], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:04] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:04] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:04] PM2 log: App [firekylin] with id [0] and pid [15286], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:04] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:04] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:04] PM2 log: App [firekylin] with id [0] and pid [15296], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:04] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:04] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:04] PM2 log: App [firekylin] with id [0] and pid [15308], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:04] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:16:04] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-05 18:16:05] PM2 log: App [firekylin] with id [0] and pid [15318], exited with code [1] via signal [SIGINT]
PM2        | [2018-05-05 18:16:05] PM2 log: Script /www/wwwroot/blog/blogproduction.js had too many unstable restarts (16). Stopped. "errored"
PM2        | [2018-05-05 18:16:58] PM2 log: Stopping app:firekylin id:0
PM2        | [2018-05-05 18:16:58] PM2 error: app=firekylin id=0 does not have a pid
PM2        | [2018-05-05 18:19:34] PM2 log: Process 0 in a stopped status, starting it
PM2        | [2018-05-05 18:19:34] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-05 18:19:34] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-13 22:19:14] PM2 log: Stopping app:firekylin id:0
PM2        | [2018-05-13 22:19:14] PM2 log: App [firekylin] with id [0] and pid [15957], exited with code [0] via signal [SIGINT]
PM2        | [2018-05-13 22:19:15] PM2 log: pid=15957 msg=process killed
PM2        | [2018-05-13 22:20:11] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-13 22:20:11] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-13 22:22:51] PM2 log: Stopping app:firekylin id:0
PM2        | [2018-05-13 22:22:51] PM2 log: App [firekylin] with id [0] and pid [7417], exited with code [0] via signal [SIGINT]
PM2        | [2018-05-13 22:22:51] PM2 log: pid=7417 msg=process killed
PM2        | [2018-05-13 22:23:36] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-13 22:23:36] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-13 22:23:47] PM2 log: Stopping app:firekylin id:0
PM2        | [2018-05-13 22:23:47] PM2 log: App [firekylin] with id [0] and pid [8051], exited with code [0] via signal [SIGINT]
PM2        | [2018-05-13 22:23:47] PM2 log: pid=8051 msg=process killed
PM2        | [2018-05-13 22:24:07] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-13 22:24:07] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-13 22:25:04] PM2 log: Process 0 in a stopped status, starting it
PM2        | [2018-05-13 22:25:04] PM2 log: Stopping app:firekylin id:0
PM2        | [2018-05-13 22:25:04] PM2 log: App [firekylin] with id [0] and pid [8199], exited with code [0] via signal [SIGINT]
PM2        | [2018-05-13 22:25:04] PM2 log: pid=8199 msg=process killed
PM2        | [2018-05-13 22:25:04] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-13 22:25:04] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-13 22:35:47] PM2 log: Process 0 in a stopped status, starting it
PM2        | [2018-05-13 22:35:47] PM2 log: Stopping app:firekylin id:0
PM2        | [2018-05-13 22:35:48] PM2 log: App [firekylin] with id [0] and pid [8386], exited with code [0] via signal [SIGINT]
PM2        | [2018-05-13 22:35:48] PM2 log: pid=8386 msg=process killed
PM2        | [2018-05-13 22:35:48] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-13 22:35:48] PM2 log: App name:firekylin id:0 online
PM2        | [2018-05-13 22:57:38] PM2 log: Stopping app:firekylin id:0
PM2        | [2018-05-13 22:57:38] PM2 log: App [firekylin] with id [0] and pid [9994], exited with code [0] via signal [SIGINT]
PM2        | [2018-05-13 22:57:38] PM2 log: pid=9994 msg=process killed
PM2        | [2018-05-13 22:57:38] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-13 22:57:38] PM2 log: App name:firekylin id:0 online

/root/.pm2/logs/firekylin-out-0.log last 100 lines:
/root/.pm2/logs/firekylin-error-0.log last 100 lines:
0|firekyli |     at new Script (vm.js:74:7)
0|firekyli |     at createScript (vm.js:246:10)
0|firekyli |     at Object.runInThisContext (vm.js:298:10)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:646:28)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:589:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:626:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at exports.interopRequire (/www/wwwroot/blog/blog/node_modules/think-loader/loader/util.js:14:13)
0|firekyli |     at allowExtends.forEach.type (/www/wwwroot/blog/blog/node_modules/think-loader/loader/extend.js:46:20)
0|firekyli |     at Array.forEach (<anonymous>)
0|firekyli |     at Object.load (/www/wwwroot/blog/blog/node_modules/think-loader/loader/extend.js:40:18)
0|firekyli |     at Loader.loadExtend (/www/wwwroot/blog/blog/node_modules/think-loader/index.js:86:19)
0|firekyli |     at thinkLoader.loadExtend (/www/wwwroot/blog/blog/node_modules/thinkjs/lib/loader.js:62:31)
0|firekyli | /www/wwwroot/blog/blognode_modules/thinkjs/lib/extend/controller.js:304
0|firekyli |   init: function(http) {
0|firekyli |   ^^^^
0|firekyli |
0|firekyli | SyntaxError: Unexpected identifier
0|firekyli |     at new Script (vm.js:74:7)
0|firekyli |     at createScript (vm.js:246:10)
0|firekyli |     at Object.runInThisContext (vm.js:298:10)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:646:28)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:589:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:626:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at exports.interopRequire (/www/wwwroot/blog/blog/node_modules/think-loader/loader/util.js:14:13)
0|firekyli |     at allowExtends.forEach.type (/www/wwwroot/blog/blog/node_modules/think-loader/loader/extend.js:46:20)
0|firekyli |     at Array.forEach (<anonymous>)
0|firekyli |     at Object.load (/www/wwwroot/blog/blog/node_modules/think-loader/loader/extend.js:40:18)
0|firekyli |     at Loader.loadExtend (/www/wwwroot/blog/blog/node_modules/think-loader/index.js:86:19)
0|firekyli |     at thinkLoader.loadExtend (/www/wwwroot/blog/blog/node_modules/thinkjs/lib/loader.js:62:31)
0|firekyli | /www/wwwroot/blog/blognode_modules/thinkjs/lib/extend/controller.js:304
0|firekyli |   init: function(http) {
0|firekyli |   ^^^^
0|firekyli |
0|firekyli | SyntaxError: Unexpected identifier
0|firekyli |     at new Script (vm.js:74:7)
0|firekyli |     at createScript (vm.js:246:10)
0|firekyli |     at Object.runInThisContext (vm.js:298:10)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:646:28)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:589:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:626:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at exports.interopRequire (/www/wwwroot/blog/blog/node_modules/think-loader/loader/util.js:14:13)
0|firekyli |     at allowExtends.forEach.type (/www/wwwroot/blog/blog/node_modules/think-loader/loader/extend.js:46:20)
0|firekyli |     at Array.forEach (<anonymous>)
0|firekyli |     at Object.load (/www/wwwroot/blog/blog/node_modules/think-loader/loader/extend.js:40:18)
0|firekyli |     at Loader.loadExtend (/www/wwwroot/blog/blog/node_modules/think-loader/index.js:86:19)
0|firekyli |     at thinkLoader.loadExtend (/www/wwwroot/blog/blog/node_modules/thinkjs/lib/loader.js:62:31)
0|firekyli | /www/wwwroot/blog/blognode_modules/thinkjs/lib/extend/controller.js:304
0|firekyli |   init: function(http) {
0|firekyli |   ^^^^
0|firekyli |
0|firekyli | SyntaxError: Unexpected identifier
0|firekyli |     at new Script (vm.js:74:7)
0|firekyli |     at createScript (vm.js:246:10)
0|firekyli |     at Object.runInThisContext (vm.js:298:10)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:646:28)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:589:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:626:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at exports.interopRequire (/www/wwwroot/blog/blog/node_modules/think-loader/loader/util.js:14:13)
0|firekyli |     at allowExtends.forEach.type (/www/wwwroot/blog/blog/node_modules/think-loader/loader/extend.js:46:20)
0|firekyli |     at Array.forEach (<anonymous>)
0|firekyli |     at Object.load (/www/wwwroot/blog/blog/node_modules/think-loader/loader/extend.js:40:18)
0|firekyli |     at Loader.loadExtend (/www/wwwroot/blog/blog/node_modules/think-loader/index.js:86:19)
0|firekyli |     at thinkLoader.loadExtend (/www/wwwroot/blog/blog/node_modules/thinkjs/lib/loader.js:62:31)
0|firekyli | /www/wwwroot/blog/blognode_modules/thinkjs/lib/extend/controller.js:304
0|firekyli |   init: function(http) {
0|firekyli |   ^^^^
0|firekyli |
0|firekyli | SyntaxError: Unexpected identifier
0|firekyli |     at new Script (vm.js:74:7)
0|firekyli |     at createScript (vm.js:246:10)
0|firekyli |     at Object.runInThisContext (vm.js:298:10)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:646:28)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:589:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:626:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at exports.interopRequire (/www/wwwroot/blog/blog/node_modules/think-loader/loader/util.js:14:13)
0|firekyli |     at allowExtends.forEach.type (/www/wwwroot/blog/blog/node_modules/think-loader/loader/extend.js:46:20)
0|firekyli |     at Array.forEach (<anonymous>)
0|firekyli |     at Object.load (/www/wwwroot/blog/blog/node_modules/think-loader/loader/extend.js:40:18)
0|firekyli |     at Loader.loadExtend (/www/wwwroot/blog/blog/node_modules/think-loader/index.js:86:19)
0|firekyli |     at thinkLoader.loadExtend (/www/wwwroot/blog/blog/node_modules/thinkjs/lib/loader.js:62:31)



```
这是加了参数之后的结果

**Comment by haima2** [comment]
问题已经解决，，，MMP以后不能瞎加
