### ISSUE TITLE
后台无法删除用户

### ISSUE THREAD

**Issue by haima2** [firekylin/firekylin#530]
今天在博客添加了一个新用户，刚刚在删除的时候总是报服务器错误。不知道应该怎么解决。
错误日志如下
```logs
0|firekyli |     at Promise._settlePromise (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:559:18)
0|firekyli |     at Promise._settlePromise0 (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:604:10)
0|firekyli |     at Promise._settlePromises (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:683:18)
0|firekyli |     at Async._drainQueue (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:138:16)
0|firekyli |     at Async._drainQueues (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
0|firekyli |     at Immediate.Async.drainQueues (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
0|firekyli |     at runCallback (timers.js:696:18)
0|firekyli |     at tryOnImmediate (timers.js:667:5)
0|firekyli |     at processImmediate (timers.js:649:5)
0|firekyli |     at process.topLevelDomainCallback (domain.js:121:23)
0|firekyli | TypeError: this.modelInstance.getPk is not a function
0|firekyli |     at module.exports.deleteAction (/www/wwwroot/blog/blog/src/admin/controller/api/user.js:61:39)
0|firekyli |     at promise.then.data (/www/wwwroot/blog/blog/node_modules/think-controller/index.js:55:32)
0|firekyli |     at tryCatcher (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23)
0|firekyli |     at Promise._settlePromiseFromHandler (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:502:31)
0|firekyli |     at Promise._settlePromise (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:559:18)
0|firekyli |     at Promise._settlePromise0 (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:604:10)
0|firekyli |     at Promise._settlePromises (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:683:18)
0|firekyli |     at Async._drainQueue (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:138:16)
0|firekyli |     at Async._drainQueues (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
0|firekyli |     at Immediate.Async.drainQueues (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
0|firekyli |     at runCallback (timers.js:696:18)
0|firekyli |     at tryOnImmediate (timers.js:667:5)
0|firekyli |     at processImmediate (timers.js:649:5)
0|firekyli |     at process.topLevelDomainCallback (domain.js:121:23)
0|firekyli | TypeError: this.modelInstance.getPk is not a function
0|firekyli |     at module.exports.deleteAction (/www/wwwroot/blog/blog/src/admin/controller/api/user.js:61:39)
0|firekyli |     at promise.then.data (/www/wwwroot/blog/blog/node_modules/think-controller/index.js:55:32)
0|firekyli |     at tryCatcher (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23)
0|firekyli |     at Promise._settlePromiseFromHandler (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:502:31)
0|firekyli |     at Promise._settlePromise (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:559:18)
0|firekyli |     at Promise._settlePromise0 (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:604:10)
0|firekyli |     at Promise._settlePromises (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:683:18)
0|firekyli |     at Async._drainQueue (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:138:16)
0|firekyli |     at Async._drainQueues (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
0|firekyli |     at Immediate.Async.drainQueues (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
0|firekyli |     at runCallback (timers.js:696:18)
0|firekyli |     at tryOnImmediate (timers.js:667:5)
0|firekyli |     at processImmediate (timers.js:649:5)
0|firekyli |     at process.topLevelDomainCallback (domain.js:121:23)
0|firekyli | TypeError: this.modelInstance.getPk is not a function
0|firekyli |     at module.exports.deleteAction (/www/wwwroot/blog/blog/src/admin/controller/api/user.js:61:39)
0|firekyli |     at promise.then.data (/www/wwwroot/blog/blog/node_modules/think-controller/index.js:55:32)
0|firekyli |     at tryCatcher (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23)
0|firekyli |     at Promise._settlePromiseFromHandler (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:502:31)
0|firekyli |     at Promise._settlePromise (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:559:18)
0|firekyli |     at Promise._settlePromise0 (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:604:10)
0|firekyli |     at Promise._settlePromises (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:683:18)
0|firekyli |     at Async._drainQueue (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:138:16)
0|firekyli |     at Async._drainQueues (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
0|firekyli |     at Immediate.Async.drainQueues (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
0|firekyli |     at runCallback (timers.js:696:18)
0|firekyli |     at tryOnImmediate (timers.js:667:5)
0|firekyli |     at processImmediate (timers.js:649:5)
0|firekyli |     at process.topLevelDomainCallback (domain.js:121:23)
0|firekyli | TypeError: this.modelInstance.getPk is not a function
0|firekyli |     at module.exports.deleteAction (/www/wwwroot/blog/blog/src/admin/controller/api/user.js:61:39)
0|firekyli |     at promise.then.data (/www/wwwroot/blog/blog/node_modules/think-controller/index.js:55:32)
0|firekyli |     at tryCatcher (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23)
0|firekyli |     at Promise._settlePromiseFromHandler (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:502:31)
0|firekyli |     at Promise._settlePromise (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:559:18)
0|firekyli |     at Promise._settlePromise0 (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:604:10)
0|firekyli |     at Promise._settlePromises (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:683:18)
0|firekyli |     at Async._drainQueue (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:138:16)
0|firekyli |     at Async._drainQueues (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
0|firekyli |     at Immediate.Async.drainQueues (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
0|firekyli |     at runCallback (timers.js:696:18)
0|firekyli |     at tryOnImmediate (timers.js:667:5)
0|firekyli |     at processImmediate (timers.js:649:5)
0|firekyli |     at process.topLevelDomainCallback (domain.js:121:23)
0|firekyli | TypeError: this.modelInstance.getPk is not a function
0|firekyli |     at module.exports.deleteAction (/www/wwwroot/blog/blog/src/admin/controller/api/user.js:61:39)
0|firekyli |     at promise.then.data (/www/wwwroot/blog/blog/node_modules/think-controller/index.js:55:32)
0|firekyli |     at tryCatcher (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23)
0|firekyli |     at Promise._settlePromiseFromHandler (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:502:31)
0|firekyli |     at Promise._settlePromise (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:559:18)
0|firekyli |     at Promise._settlePromise0 (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:604:10)
0|firekyli |     at Promise._settlePromises (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:683:18)
0|firekyli |     at Async._drainQueue (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:138:16)
0|firekyli |     at Async._drainQueues (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
0|firekyli |     at Immediate.Async.drainQueues (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
0|firekyli |     at runCallback (timers.js:696:18)
0|firekyli |     at tryOnImmediate (timers.js:667:5)
0|firekyli |     at processImmediate (timers.js:649:5)
0|firekyli |     at process.topLevelDomainCallback (domain.js:121:23)
0|firekyli | TypeError: this.modelInstance.getPk is not a function
0|firekyli |     at module.exports.deleteAction (/www/wwwroot/blog/blog/src/admin/controller/api/user.js:61:39)
0|firekyli |     at promise.then.data (/www/wwwroot/blog/blog/node_modules/think-controller/index.js:55:32)
0|firekyli |     at tryCatcher (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23)
0|firekyli |     at Promise._settlePromiseFromHandler (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:502:31)
0|firekyli |     at Promise._settlePromise (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:559:18)
0|firekyli |     at Promise._settlePromise0 (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:604:10)
0|firekyli |     at Promise._settlePromises (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:683:18)
0|firekyli |     at Async._drainQueue (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:138:16)
0|firekyli |     at Async._drainQueues (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
0|firekyli |     at Immediate.Async.drainQueues (/www/wwwroot/blog/blog/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
0|firekyli |     at runCallback (timers.js:696:18)
0|firekyli |     at tryOnImmediate (timers.js:667:5)
0|firekyli |     at processImmediate (timers.js:649:5)
0|firekyli |     at process.topLevelDomainCallback (domain.js:121:23)

```

**Comment by haima2** [comment]
看F12网络请求的时候发现：{errno: 500, errmsg: "this.modelInstance.getPk is not a function"}

**Comment by haima2** [comment]
顺便说一下，新建了一个用户之后，新建的账号是投稿者权限，登陆后台登录不上，提示ACCOUNT_FORBIDDEN
所以打算删了重弄，然后发现删除不了

**Comment by wei** [comment]
感谢汇报。@lizheming thinkjs/thinkjs#853 这样改可以吗？把 `/www/wwwroot/blog/blog/src/admin/controller/api/user.js` 里的 
```
let pk = await this.modelInstance.getPk();
``` 
改成 
```
let pk = this.modelInstance.pk;
```

**Comment by lizheming** [comment]
@wei 可以的

**Comment by wei** [comment]
@haima2 你试试 😄

**Comment by haima2** [comment]
改完之后重启服务又变成502了

**Comment by haima2** [comment]
好了，谢谢
