### ISSUE TITLE
v1 版本安装不上

### ISSUE THREAD

**Issue by Aprilor** [firekylin/firekylin#545]
当我和数据库对接后 点击下一步 浏览器就显示“OK”这两个字母  也没有什么反应 页面也不跳转
大佬 请问这是什么问题

**Comment by Aprilor** [comment]
![image](https://user-images.githubusercontent.com/38257053/41840337-16e69586-7898-11e8-9dd8-783370706daa.png)

**Comment by Aprilor** [comment]
![image](https://user-images.githubusercontent.com/38257053/41840603-c45b0bac-7898-11e8-90d2-cb6b76b979d4.png)
这是我在Mac安装的

**Comment by lizheming** [comment]
F12 看一下静态资源的加载是否有问题？看起来你之前的安装有问题有一些参数没有录入。

**Comment by haima2** [comment]
现在安装依赖的时候sqlite3装不上，源码下载地址403了，他们也没更新，GG咯。
```errorinfo
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.5.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.5.0 (node-v64 ABI) (falling back to source compile with node-gyp)

```

**Comment by lizheming** [comment]
@haima2 我的问题...我之后发个版本把这个依赖删掉。目前你可以手动去 package.json 里面把 `think-model-sqlite` 这个依赖删除来解决。

**Comment by haima2** [comment]
好的，谢谢

**Comment by Aprilor** [comment]
![2018-06-28 10 26 27](https://user-images.githubusercontent.com/38257053/42009682-0b6eaa04-7abe-11e8-9f37-a5e95710c81c.png)
是安装的时候出了问题，但是安装v0版本的 npm install 都是可以的，到v1就有错误，这是什么原因

**Comment by haima2** [comment]
跑的好好的为啥Nginx返回502呢，端口也监听了啊，依赖也去掉了啊，
```bash
# lsof -i tcp:8360
COMMAND   PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
node    20008 root   13u  IPv4 5529205      0t0  TCP *:8360 (LISTEN)

```
```bash
# pm2 logs firekylin --lines 100
[TAILING] Tailing last 100 lines for [firekylin] process (change the value with --lines option)
/root/.pm2/logs/firekylin-out-0.log last 100 lines:
/root/.pm2/logs/firekylin-error-0.log last 100 lines:
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
0|firekyli | Error: Cannot find module '/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
0|firekyli |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:650:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at Object.<anonymous> (/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/sqlite3.js:4:15)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:702:30)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:612:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
0|firekyli | Error: Cannot find module '/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
0|firekyli |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:650:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at Object.<anonymous> (/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/sqlite3.js:4:15)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:702:30)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:612:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
0|firekyli | Error: Cannot find module '/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
0|firekyli |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:650:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at Object.<anonymous> (/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/sqlite3.js:4:15)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:702:30)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:612:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
0|firekyli | Error: Cannot find module '/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
0|firekyli |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:650:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at Object.<anonymous> (/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/sqlite3.js:4:15)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:702:30)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:612:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
0|firekyli | Error: Cannot find module '/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
0|firekyli |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:650:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at Object.<anonymous> (/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/sqlite3.js:4:15)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:702:30)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:612:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
0|firekyli | Error: Cannot find module '/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
0|firekyli |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:650:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at Object.<anonymous> (/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/sqlite3.js:4:15)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:702:30)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:612:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
0|firekyli | Error: Cannot find module '/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
0|firekyli |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:650:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at Object.<anonymous> (/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/sqlite3.js:4:15)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:702:30)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:612:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
0|firekyli | Error: Cannot find module '/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
0|firekyli |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:650:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at Object.<anonymous> (/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/sqlite3.js:4:15)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:702:30)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:612:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
0|firekyli | Error: Cannot find module '/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
0|firekyli |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
0|firekyli |     at Module.require (internal/modules/cjs/loader.js:650:17)
0|firekyli |     at require (internal/modules/cjs/helpers.js:20:18)
0|firekyli |     at Object.<anonymous> (/www/wwwroot/www.haimablog.ooo/firekylin/node_modules/sqlite3/lib/sqlite3.js:4:15)
0|firekyli |     at Module._compile (internal/modules/cjs/loader.js:702:30)
0|firekyli |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
0|firekyli |     at Module.load (internal/modules/cjs/loader.js:612:32)
0|firekyli |     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
0|firekyli |     at Function.Module._load (internal/modules/cjs/loader.js:543:3)

```
@lizheming  这咋整

**Comment by haima2** [comment]
现在好了，但是css和js都返回404，实际文件是存在的，而且直接访问也没问题，，，，但是在页面里调用的就返回404

**Comment by wei** [comment]
直接访问没问题 nginx访问有问题就是nginx配置问题 请贴conf

**Comment by haima2** [comment]
nginx的conf如下
```nginx
server
{
    listen 80;
	listen 443 ssl http2;
    server_name www.haimablog.ooo haimablog.ooo;
    index index.js index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/www.haimablog.ooo/firekylin;
    set $node_port 8360;
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #HTTP_TO_HTTPS_START
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    #HTTP_TO_HTTPS_END
    ssl_certificate    /etc/letsencrypt/live/www.haimablog.ooo/fullchain.pem;
    ssl_certificate_key    /etc/letsencrypt/live/www.haimablog.ooo/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:!aNULL:!MD5:!RC4:!DHE:!WEEK:!NULL:!aWEEK:!eNULL:!EXPORT:!DES:!PSK:!3DES:!SHA:!TLSv1.0;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497  https://$host$request_uri;

    #SSL-END
    
    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    error_page 404 /404.html;
    error_page 502 /502.html;
    #ERROR-PAGE-END
    
    #PHP-INFO-START  PHP引用配置，可以注释或修改
   # include enable-php-00.conf;
    #PHP-INFO-END
    
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/www.haimablog.ooo.conf;
    #REWRITE-END
    
    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        try_files $uri = 404;
    }
    
    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log off;
        access_log off;
    }
    
    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log off;
        access_log off; 
    }
    
     location / {
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:$node_port$request_uri;
        proxy_redirect off;
    }

    location = /development.js {
        deny all;
    }
    location = /testing.js {
        deny all;
    }

    location = /production.js {
        deny all;
    }


    location ~ /static/ {
        etag         on;
        expires      max;
    }



	#add_header Accept-Encoding "br";
    
    #安全配置-开始
    #安全配置-结束
    access_log  off;
    error_log  /www/wwwlogs/www.haimablog.ooo.error.log;
}

```

**Comment by wei** [comment]
location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log off;
        access_log off;
    }
    
    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log off;
        access_log off; 
    }


目测这两个和下面的static冲突了  

请使用官方提供的conf再把你自己的规则慢慢加回去

**Comment by haima2** [comment]
哦哦，我试试

**Comment by haima2** [comment]
去掉了也不行呀，还是404

**Comment by wei** [comment]
请尝试一下官方的conf

**Comment by haima2** [comment]
嗯嗯

**Comment by Aprilor** [comment]
@lizheming 根本的问题还是没有解决，在浏览器安装的时候，对接数据库有点问题是不是对接不上，第二个安装页面，我把账户什么都设置好了，点击开始安装后就出现上面 图2 的一串错误，我去查看数据库，里面竟然是空的，一个表都没有

**Comment by lizheming** [comment]
@Aprilor 你的问题已 fix 详见相关 commit，请重新下载包安装即可。
