### ISSUE TITLE
在线升级到1.2.0版本，目前变成502的状态

### ISSUE THREAD

**Issue by kpax02** [firekylin/firekylin#586]
我直接通过在线更新了版本，更新完后，一开始页面还能正常访问，但admin后台各个组件点击都提示Component failed to load，然后我在后面试着通过`pm2 restart pm2.json`命令重启，结果就直接502了，执行`node production.js`，会有如下信息：

`Error: Cannot find module 'request-promise-native'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/firekylin/src/admin/service/feed.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
`

**Comment by lizheming** [comment]
启动的问题重装下依赖试试吧，在线更新可能依赖安装有点问题了。

**Comment by kpax02** [comment]
> 启动的问题重装下依赖试试吧，在线更新可能依赖安装有点问题了。


我通过`npm install --save request` 和`npm install --save request-promise-native`增加了报错相关的依赖，目前使用`node production.js`不会再报类似的错误，显示结果如下：

`(node:16173) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:16173) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
(node:16162) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
{ AssertionError [ERR_ASSERTION]: router.match must be a RegExp
    at rules.some.item (/opt/firekylin/node_modules/think-router/router.js:136:9)
    at Array.some (<anonymous>)
    at Router.getMatchedRule (/opt/firekylin/node_modules/think-router/router.js:129:11)
    at Router.run (/opt/firekylin/node_modules/think-router/router.js:266:30)
    at router (/opt/firekylin/node_modules/think-router/index.js:100:21)
    at dispatch (/opt/firekylin/node_modules/koa-compose/index.js:42:32)
    at parseBody.then.body (/opt/firekylin/node_modules/think-payload/index.js:47:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
`

页面前端正常显示，版本也升到了1.2.0，后台的所有功能点击后还是提示
 ` Error!Component failed to load`

**Comment by qfdk** [comment]
今天安装了1.2.1版本 还是出现 Error!Component failed to load

**Comment by colordove** [comment]
@qfdk 1.2.2版本修复了问题，重新安装下看看呢

**Comment by colordove** [comment]
@qfdk 1.2.1已经修复了，出问题是因为在线更新的包不对，1.2.2更新了这个包，所以没有反应在commit上，看到gitter上你已经确认修复啦

**Comment by colordove** [comment]
@kpax02 能私我下你博客地址我去看看么，hujian201@gmail.com

**Comment by kpax02** [comment]
@colordove 抱歉，才看到消息，我把整个firekylin目录删除后重新下载安装，在清了缓存以后目前已经正常，中间在console里有看到类似`webpackJsonp is not a function`的错误
