### ISSUE TITLE
在线升级1.2.2 后，Error!Component failed to load

### ISSUE THREAD

**Issue by opsarno** [firekylin/firekylin#593]
升级前版本：FireKylin版本：1.1.1
升级后版本：FireKylin版本：1.2.2

```bash
系统概况

    服务器系统：linux
    Node.js版本：8.11.1
    V8引擎版本：6.2.414.50
    MySQL版本：5.5.60-MariaDB
    ThinkJS版本：3.2.7
    FireKylin版本：1.2.2
```

现状：
后台可以登录，概述能够正常打开预览。但是其它所有标签点击报错：
```bash
 Error!Component failed to load 
```

查看日志：
```bash
$ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/work/.pm2/pm2.log last 15 lines:
PM2        | [2018-05-16 16:37:57] PM2 log: Stopping app:firekylin id:0
PM2        | [2018-05-16 16:37:57] PM2 log: App [firekylin] with id [0] and pid [7282], exited with code [0] via signal [SIGINT]
PM2        | [2018-05-16 16:37:57] PM2 log: pid=7282 msg=process killed
PM2        | [2018-05-16 20:29:36] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-05-16 20:29:36] PM2 log: App name:firekylin id:0 online
PM2        | [2018-06-04 16:43:49] PM2 log: Stopping app:firekylin id:0
PM2        | [2018-06-04 16:43:50] PM2 log: App [firekylin] with id [0] and pid [7819], exited with code [0] via signal [SIGINT]
PM2        | [2018-06-04 16:43:50] PM2 log: pid=7819 msg=process killed
PM2        | [2018-06-04 16:46:20] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-06-04 16:46:20] PM2 log: App name:firekylin id:0 online
PM2        | [2018-11-12 16:47:27] PM2 log: Stopping app:firekylin id:0
PM2        | [2018-11-12 16:47:27] PM2 log: App [firekylin] with id [0] and pid [8433], exited with code [0] via signal [SIGINT]
PM2        | [2018-11-12 16:47:27] PM2 log: pid=8433 msg=process killed
PM2        | [2018-11-12 16:47:27] PM2 log: Starting execution sequence in -fork mode- for app name:firekylin id:0
PM2        | [2018-11-12 16:47:27] PM2 log: App name:firekylin id:0 online

/home/work/.pm2/logs/firekylin-out-0.log last 15 lines:
/home/work/.pm2/logs/firekylin-error-0.log last 15 lines:
0|firekyli |     at Async._drainQueues (/opt/web/firekylin/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
0|firekyli |     at Immediate.Async.drainQueues (/opt/web/firekylin/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
0|firekyli |     at runCallback (timers.js:794:20)
0|firekyli |     at tryOnImmediate (timers.js:752:5)
0|firekyli |     at processImmediate [as _immediateCallback] (timers.js:729:5)
0|firekyli |   message: 'url `/wp-content/plugins/wp-front-end-repository/js/uploadify/uploadify.css` not found.' }
0|firekyli | Process disconnected from parent !
0|firekyli | Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
0|firekyli |     at process.target.send (internal/child_process.js:588:16)
0|firekyli |     at ipcSend (/opt/soft/node-v8.11.1-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/utils/transport.js:22:13)
0|firekyli |     at Object.Transport.send (/opt/soft/node-v8.11.1-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/utils/transport.js:33:3)
0|firekyli |     at Timeout._onTimeout (/opt/soft/node-v8.11.1-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/Probe.js:138:17)
0|firekyli |     at ontimeout (timers.js:482:11)
0|firekyli |     at Timer.unrefdHandle (timers.js:595:5)
0|firekyli | Mon, 12 Nov 2018 08:44:20 GMT logic deprecated logic's __after method is deprecated, it will be discarded in the next version  at node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23

0|firekyli | Mon, 12 Nov 2018 08:47:44 GMT logic deprecated logic's __after method is deprecated, it will be discarded in the next version  at node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23

```

**Comment by lizheming** [comment]
清一下浏览器缓存

**Comment by opsarno** [comment]
@lizheming 可以了，谢谢！

PS：不过清完缓存后，首次点击文章管理 Loading... 时间比之前版本耗时多了。我目前就20篇文章。

**Comment by lizheming** [comment]
和文章数无关，后台前端做了重构，做了分块加载，Loading 是在下载前端的分块 JS 文件。

**Comment by opsarno** [comment]
OK  没有问题了。 期待后续的更新与优化。谢啦。
