### ISSUE TITLE
TypeError: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by opsarno** [firekylin/firekylin#761]
就在分类管理里面删除了一个分类，前端页面就打不开了，显示 Internal Server Error 500 错误。

admin 后台管理页面依旧可以正常打开访问。

错误日志如下：
```bash
0|production  | TypeError: Cannot read property 'children' of undefined
0|production  |     at module.exports.getCateArchive (/opt/web/firekylin/src/home/model/cate.js:75:23)
0|production  |     at <anonymous>
0|production  |     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

怎么解决呢？

**Comment by lizheming** [comment]
我看了下代码，你应该是把一个一级分类删除了，但是这个一级分类之前有子分类，所以代码报错了，你进数据库清一下那个分类的  `pid`，或者把那个子分类删除应该都可以。

**Comment by opsarno** [comment]
```sql
mysql> select * from fk_cate;
+----+--------+-----+-----------+
| id | name   | pid | pathname  |
+----+--------+-----+-----------+
|  1 | Linux  |   0 | linux     |
|  2 | Python |   0 | python    |
|  6 | Mysql  |   3 | mysql     |
+----+--------+-----+-----------+
5 rows in set (0.00 sec)

mysql> delete from fk_cate where pid=3;
Query OK, 1 row affected (0.01 sec)
```

已解决。
